version: '3.9'

services:
  app:
    container_name: app
    restart: always
    command: python3 __main__.py
    env_file: .env
    build:
      context: ./app
      dockerfile: app.dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    restart: always
    env_file: .env
    build:
      context: ./front
      dockerfile: front.dockerfile
    depends_on:
      - app
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      # - ./static:/etc/nginx/static_img
    ports:
      - 80:80
      - 443:443

  db:
    container_name: db
    image: postgres:latest
    env_file: db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
